package selenium;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;


public class BusbookinTask {

	public static void main(String[] args) throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "./softwares/chromedriver.exe");
		ChromeOptions opt=new ChromeOptions();
		Thread.sleep(1000);
		opt.addArguments("--disable-notifications");
		Thread.sleep(1000);
		WebDriver driver=new ChromeDriver(opt);
		driver.manage().window().maximize();
		driver.get("https://www.busonlineticket.com/booking/bus-tickets.aspx");
		Thread.sleep(2000);
		WebElement src=driver.findElement(By.id("txtOriginGeneral"));
		src.click();
		Thread.sleep(1000);
		WebElement src1=driver.findElement(By.xpath("(//div[@class='select2-result-label'])[2]"));
		src1.click();
		Thread.sleep(1000);
		WebElement dst=driver.findElement(By.id("txtDestinationGeneral"));
		dst.click();
		Thread.sleep(1000);
		WebElement dst1=driver.findElement(By.xpath("(//div[@class='select2-result-label'])[2]"));
		dst1.click();
		Thread.sleep(1000);
//		WebElement date=driver.findElement(By.id("txtReturnDateBooking"));
//		date.click();
//		Thread.sleep(1000);
		WebElement mon=driver.findElement(By.id("ui-datepicker-div"));
		mon.click();
		Thread.sleep(1000);
		WebElement monarr=driver.findElement(By.xpath("//a[@class='ui-datepicker-next ui-corner-all']"));
		monarr.click();
		Thread.sleep(1000);
//		WebElement mon1=driver.findElement(By.xpath("//div[@id='ui-datepicker-div']"));
//		mon1.click();
//		Thread.sleep(1000);
		WebElement date1=driver.findElement(By.xpath("//a[.='20']"));
		date1.click();
		Thread.sleep(1000);
//		WebElement monr=driver.findElement(By.id("ui-datepicker-div"));
//		monr.click();
//		Thread.sleep(1000);
		WebElement date=driver.findElement(By.id("txtReturnDateBooking"));
		date.click();
		Thread.sleep(1000);
//		WebElement monret=driver.findElement(By.xpath("//a[@class='ui-datepicker-next ui-corner-all']"));
//		monret.click();
//		Thread.sleep(1000);
		WebElement date2=driver.findElement(By.xpath("//a[.='22']"));
		date2.click();
		Thread.sleep(1000);
		WebElement btn=driver.findElement(By.id("btnBusSearchNewGeneral"));
		btn.click();
		Thread.sleep(1000);
		WebElement bus1=driver.findElement(By.xpath("//div[@class='trip-item trip-item-lg'][1]"));
		bus1.click();
		Thread.sleep(1000);
		WebElement sel=driver.findElement(By.xpath("(//button[@class='btn btn-orange mt-2 selectseatbutton'])[1]"));
		sel.click();
		Thread.sleep(1000);
		WebElement seat1=driver.findElement(By.xpath("(//div[@class='seat'])[1]"));
		seat1.click();
		Thread.sleep(2000);
		WebElement seat2=driver.findElement(By.xpath("(//div[@class='seat'])[2]"));
		seat2.click();
		Thread.sleep(1000);
		WebElement seat3=driver.findElement(By.xpath("(//div[@class='seat'])[3]"));
		seat3.click();
		Thread.sleep(1000);
		WebElement seat4=driver.findElement(By.xpath("(//div[@class='seat'])[4]"));
		seat4.click();
		Thread.sleep(1000);
		WebElement seat5=driver.findElement(By.xpath("(//div[@class='seat'])[5]"));
		seat5.click();
		Thread.sleep(1000);
		WebElement seat6=driver.findElement(By.xpath("(//div[@class='seat'])[6]"));
		seat6.click();
		Thread.sleep(1000);
		WebElement proc=driver.findElement(By.xpath("(//span[.='Proceed'])[2]"));
		proc.click();
		Thread.sleep(1000);
		WebElement pp=driver.findElement(By.xpath("//div[@class='cta-buttons']"));
		pp.click();
		Thread.sleep(1000);
		WebElement bus2=driver.findElement(By.xpath("//div[@class='trip-item trip-item-lg'][1]"));
		bus2.click();
		Thread.sleep(1000);
		WebElement sel2=driver.findElement(By.id("BOT34F0A7E7CB34AFEA81853FDA90B177A5"));
		sel2.click();
		Thread.sleep(1000);
		WebElement seat21=driver.findElement(By.xpath("(//div[@class='seat'])[1]"));
		seat21.click();
		Thread.sleep(2000);
		WebElement seat22=driver.findElement(By.xpath("(//div[@class='seat'])[2]"));
		seat22.click();
		Thread.sleep(1000);
		WebElement seat23=driver.findElement(By.xpath("(//div[@class='seat'])[3]"));
		seat23.click();
		Thread.sleep(1000);
		WebElement seat24=driver.findElement(By.xpath("(//div[@class='seat'])[4]"));
		seat24.click();
		Thread.sleep(1000);
		WebElement seat25=driver.findElement(By.xpath("(//div[@class='seat'])[5]"));
		seat25.click();
		Thread.sleep(1000);
		WebElement seat26=driver.findElement(By.xpath("(//div[@class='seat'])[6]"));
		seat26.click();
		Thread.sleep(1000);
		WebElement proc2=driver.findElement(By.xpath("(//span[.='Proceed'])[2]"));
		proc2.click();
		Thread.sleep(1000);
		WebElement fn=driver.findElement(By.xpath("//input[@class='payment_textName form-control pay-form-control']"));
		fn.sendKeys("abc");
		Thread.sleep(1000);
		WebElement mob=driver.findElement(By.xpath("payment_txtPhoneLogin form-control pay-form-control"));
		mob.sendKeys("1234567890");
		Thread.sleep(1000);
		WebElement em=driver.findElement(By.xpath("//input[@class='payment_txtEmail form-control pay-form-control']"));
		em.sendKeys("1234@gmail.com");
		Thread.sleep(1000);
		WebElement nxbn=driver.findElement(By.id("btnNext"));
		nxbn.click();
		Thread.sleep(5000);
		driver.quit();
		

	}

}
